# Generated by Django 4.0.4 on 2022-06-16 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporte', '0001_initial'),
        ('paquete', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=8, unique=True)),
                ('pagado', models.BooleanField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquete.catalogo')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserva.pago')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporte.reporte')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
