# Generated by Django 4.0.4 on 2022-06-16 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
        ('reserva', '0002_remove_reserva_user_alter_reserva_reporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='reporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporte.reporte'),
        ),
    ]
