# Generated by Django 4.0.4 on 2022-06-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('reserva', '0003_alter_reserva_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.persona'),
        ),
    ]
