# Generated by Django 4.0.4 on 2022-06-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('dui', models.CharField(default='None', max_length=10)),
                ('nit', models.CharField(default='None', max_length=14)),
                ('permiso_residencia', models.CharField(default='None', max_length=10)),
                ('pasaporte', models.CharField(default='None', max_length=10)),
                ('sexo', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('pais_residencia', models.CharField(max_length=20)),
            ],
        ),
    ]
