# Generated by Django 4.0.4 on 2022-06-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=None, max_length=8, unique=True)),
                ('disponible', models.BooleanField()),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquete.catalogo')),
                ('especificacionpaquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquete.especificacionpaquete')),
            ],
        ),
    ]
