# Generated by Django 4.0.4 on 2022-06-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionpaquete',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especificacionpaquete',
            name='numeroDias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='especificacionpaquete',
            name='numeroPersonas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
